### ISSUE TITLE
StartNow() does not seem to work with WithCronSchedule()

### ISSUE THREAD

**Issue by TheGameSquid** [dtinteractive/Topshelf.Integrations#15]
When using the following Schedule with Quartz:

```cs
x.ScheduleQuartzJobAsService(q =>
                    q.WithJob(() =>
                        JobBuilder.Create<Scraper>().Build())
                    .AddTrigger(() =>
                        TriggerBuilder.Create()
                            .WithCronSchedule("0 0 0/1 1/1 * ? *")
                            .StartNow()
                            .Build())
                );
```

The job only starts at the first hour. It does not start immediately. When using the Simple scheduler, StartNow() does seem to work properly.

**Comment by markhuber** [comment]
Those methods are provided directly by the Quartz interface. I have seen similar oddities using the Cron Schedule and so we expose a WebApi if we need runs other than the cron schedule. I doubt mixing these two methods is supported.
