### ISSUE TITLE
Topshelf.Quartz should be signed

### ISSUE THREAD

**Issue by p3nt4x0r** [dtinteractive/Topshelf.Integrations#23]
To use the very handy library in an enterprise environment and to be able to deploy the assembly to the GAC, it needs to have a strong name.
Please add signing to the project!

**Comment by skolima** [comment]
Please don't, or if you do, distribute it as a separate version. You can sign the binary yourself if you really need to deploy it to GAC (hint: you don't. NuGet works better).

Also: see how Microsoft themselves are moving away from GAC for everything that doesn't absolutely require it, including moving types away from the core libraries into NuGet-based distribution.

**Comment by p3nt4x0r** [comment]
Of course I have signed the library by myself in the meantime. Signing assemblies is just best practice, even if it is not published to the GAC.

I am aware, that there are much better ways than the GAC, but if you are forced to use the GAC because of 3rd party software running your code, there is no other way.

**Comment by markhuber** [comment]
I think I'm going to have to agree with @skolima on this one. Given that more and more of the .NET model seems to be moving away from gac and more to bin deployment, I don't see the value in dealing with signing (and strong naming, which is the bigger pain IMO).
