### ISSUE TITLE
Quartz Scheduler doesn't shutdown anymore

### ISSUE THREAD

**Issue by skolima** [dtinteractive/Topshelf.Integrations#24]
Since the last release, Quartz+TopShelf doesn't terminate properly anymore. Pressing Ctrl+C or shutting down the Windows service leaves the executable still running.

I'm reasonably certain this is due to change in https://github.com/dtinteractive/Topshelf.Integrations/blob/89d9b121ef28eaadd71c769c8170d926dcbbe99b/Source/Topshelf.Quartz/SchedulejobServiceConfiguratorExtensions.cs#L138 

introduced in 5260b67a4581b6c2cc4bab9ccddcd1edbfe1d8bc . Seems that the change https://github.com/dtinteractive/Topshelf.Integrations/commit/5260b67a4581b6c2cc4bab9ccddcd1edbfe1d8bc#diff-c522a1363e6aa9ff9d737c0c68c534a5 might have been commited by mistake?

**Comment by markhuber** [comment]
Good catch, thank you. I'll be revving the Topshelf.Quartz version soon.
