### ISSUE TITLE
Shutdown service from job

### ISSUE THREAD

**Issue by Zabaa** [dtinteractive/Topshelf.Integrations#26]
Hi. Is it possible to shutdown whole service from Execute method of IJob ? Right now all I can do is delete job. E.g if I catch specific exception in job I would like to make log and shutdown service.

Thanks for any answer.

**Comment by markhuber** [comment]
I've never really considered this use case. You could try Environment.Exit(errorCode) but that's going to forcefully exit the process skipping any cleanup routines you might have.

https://msdn.microsoft.com/en-us/library/system.environment.exit(v=vs.110).aspx

Generally speaking I'm not sure it's a good separation to give knowledge of Topshelf to Quartz, right now Quartz has no dependency on the Topshelf abstractions.

I'd suspect that the windows service handler will apply any restart rules of the service and fire it right back up a few times, so pay close attention to that.

**Comment by markhuber** [comment]
A better pattern might be to have the Topshelf service class running continually checking for failed jobs. Have the jobs mark something as they finished indicating failure. At that point have the Topshelf service class break out of a checking loop and complete, that will cause the process to end gracefully.
