### ISSUE TITLE
Question combining use cases

### ISSUE THREAD

**Issue by Jogai** [dtinteractive/Topshelf.Integrations#34]
I have a service that does some processing on a database. Now I have to build a web api on top of that same database. Can I host the web api in the same processing service? Should I?

**Comment by thealah** [comment]
I don't see why not. We have several services that both act as processors that listen for messages and host a web api endpoint.

**Comment by thealah** [comment]
Actually, we also have one service that runs on a schedule (nightly) and has a web api endpoint. That's probably very similar to what you are describing.

**Comment by Jogai** [comment]
Yes it is, thanks for the quick reply!
