### ISSUE TITLE
Error activating IScheduler

### ISSUE THREAD

**Issue by benfoster** [dtinteractive/Topshelf.Integrations#6]
When using the Ninject and Quartz integrations with the following code:

        static void Main()
        {
            HostFactory.Run(c =>
            {
                c.UseNinject(new WorkerModule());
                c.UseQuartzNinject();

                c.ScheduleQuartzJobAsService(q =>
                        q.WithJob(() =>
                            JobBuilder.Create<NotificationsJob>().Build())
                        .AddTrigger(() =>
                            TriggerBuilder.Create()
                                .WithSimpleSchedule(builder => builder
                                    .WithIntervalInSeconds(60)
                                    .RepeatForever())
                                .Build())
                );
            });
        }

Error:

>An exception of type 'Ninject.ActivationException' occurred in Ninject.dll but was not >handled in user code
>
>Additional information: Error activating IScheduler

I was under the assumption that this would configure `IScheduler` automatically?

**Comment by markhuber** [comment]
Made Ninject.Extensions.Quartz a listed dependency in the nuspec in 0.4.0 release.
